const WEATHER_API_KEY = process.env.NEXT_PUBLIC_WEATHER_API_KEY;
const STORE_API_DOMAIN = process.env.NEXT_PUBLIC_STORE_API_DOMAIN;
export const EMAIL_TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAIL_TEMPLATE_ID;
export const EMAIL_SERVICE_ID = process.env.NEXT_PUBLIC_EMAIL_SERVICE_ID;
export const EMAIL_PUBLIC_KEY = process.env.NEXT_PUBLIC_EMAIL_PUBLIC_KEY;

export { WEATHER_API_KEY, STORE_API_DOMAIN };
